version: '2'

services:
  lb:
   image: dockercloud/haproxy:latest
   depends_on:
    - web
   ports:
    - "8080:80"
   environment:
    - BALANCE=roundrobin
    - ADDITIONAL_SERVICES=dockermyappacs:web
   links:
    - web
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
 
  web:
#    build: .
    image: larryms/lnchello
    expose:
     - "5000"
    depends_on:
     - redis

  redis:
    image: redis

